export default function getType(val: any): string;
export declare const isVisible: (el: HTMLElement, visibility?: boolean) => boolean;
export declare const getDataOptions: (el: HTMLElement, evtName: string) => Object;
export declare const docTop: () => number;
export declare const noop: () => void;
export declare const isHidden: (el: any) => boolean;
export declare const kebabCase: (str: string) => string;
export declare const camelCase: (str: string) => string;
export declare const capitalize: (str: string) => string;
export declare const isMobileOS: () => boolean;
